// 📝 プリセットテーマの定義
import { Theme } from '@/types/theme';

export const presetThemes: Record<string, Theme> = {
  light: {
    id: 'light',
    name: 'ライト',
    isDark: false,
    colors: {
      primary: '#ff0033',
      secondary: '#6b7280',
      background: '#ffffff',
      surface: '#f9fafb',
      text: {
        primary: '#111827',
        secondary: '#6b7280',
        disabled: '#9ca3af',
      },
      accent: '#3b82f6',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      border: '#e5e7eb',
    },
  },
  dark: {
    id: 'dark',
    name: 'ダーク',
    isDark: true,
    colors: {
      primary: '#ff4d6e',
      secondary: '#9ca3af',
      background: '#111827',
      surface: '#1f2937',
      text: {
        primary: '#f9fafb',
        secondary: '#d1d5db',
        disabled: '#6b7280',
      },
      accent: '#60a5fa',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      border: '#374151',
    },
  },
  'high-contrast': {
    id: 'high-contrast',
    name: 'ハイコントラスト',
    isDark: true,
    colors: {
      primary: '#ffffff',
      secondary: '#ffffff',
      background: '#000000',
      surface: '#1a1a1a',
      text: {
        primary: '#ffffff',
        secondary: '#ffffff',
        disabled: '#888888',
      },
      accent: '#00ffff',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      border: '#ffffff',
    },
  },
  blue: {
    id: 'blue',
    name: 'ブルー',
    isDark: false,
    colors: {
      primary: '#1e40af',
      secondary: '#64748b',
      background: '#f8fafc',
      surface: '#e0f2fe',
      text: {
        primary: '#0f172a',
        secondary: '#475569',
        disabled: '#94a3b8',
      },
      accent: '#0ea5e9',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      border: '#cbd5e1',
    },
  },
  green: {
    id: 'green',
    name: 'グリーン',
    isDark: false,
    colors: {
      primary: '#059669',
      secondary: '#6b7280',
      background: '#f0fdf4',
      surface: '#dcfce7',
      text: {
        primary: '#14532d',
        secondary: '#374151',
        disabled: '#9ca3af',
      },
      accent: '#10b981',
      success: '#22c55e',
      warning: '#eab308',
      error: '#ef4444',
      border: '#bbf7d0',
    },
  },
  pink: {
    id: 'pink',
    name: 'ピンク',
    isDark: false,
    colors: {
      primary: '#be185d',
      secondary: '#6b7280',
      background: '#fdf2f8',
      surface: '#fce7f3',
      text: {
        primary: '#831843',
        secondary: '#374151',
        disabled: '#9ca3af',
      },
      accent: '#ec4899',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      border: '#f9a8d4',
    },
  },
};